from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.models.school_model import School
from app.models.school_model import School
from app.api.auth_controller import get_current_user
from app.models.user_model import User
import zipfile
import io

router = APIRouter()

def generate_nginx_conf(school: School) -> str:
    return f"""worker_processes  1;
events {{ worker_connections 1024; }}
http {{
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    server {{
        listen {school.nginx_port};
        root {school.storage_path.replace(chr(92), '/')};
        autoindex off;
        location / {{
            limit_except GET HEAD OPTIONS {{ deny all; }}
            add_header Accept-Ranges bytes;
            add_header Cache-Control "public, max-age=3600";
            add_header Access-Control-Allow-Origin "*";
            try_files $uri $uri/ =404;
        }}
        location ~* \\.(mp4|webm|avi|mov|mkv)$ {{
            limit_except GET HEAD OPTIONS {{ deny all; }}
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin "*";
            mp4;
            mp4_buffer_size 1m;
            mp4_max_buffer_size 5m;
        }}
        location ~* \\.pdf$ {{
            limit_except GET HEAD OPTIONS {{ deny all; }}
            add_header Content-Type application/pdf;
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin "*";
            add_header Content-Disposition inline;
        }}
    }}
}}"""

def generate_sync_bat(school: School, folders: list) -> str:
    lines = [
        "@echo off",
        f"echo ======================================== >> {school.storage_path}\\sync_log.txt",
        f"echo Sync Started: %date% %time% >> {school.storage_path}\\sync_log.txt",
        ""
    ]
    for folder in folders:
        lines.append(f'REM {folder} sync')
        lines.append(
            f'D:\\MinIO\\rclone.exe --config "C:\\Users\\admin\\AppData\\Roaming\\rclone\\rclone.conf" '
            f'sync "aws-s3:easylearn1/{folder}" "{school.storage_path}\\{folder}" '
            f'--log-file={school.storage_path}\\sync_log.txt --log-level INFO --transfers 5 --retries 3'
        )
        lines.append("")
    lines.append(f"echo Sync Complete: %date% %time% >> {school.storage_path}\\sync_log.txt")
    return "\n".join(lines)

def generate_backup_bat(school: School) -> str:
    return f"""@echo off
echo ======================================== >> {school.storage_path}\\backup_log.txt
echo Backup Started: %date% %time% >> {school.storage_path}\\backup_log.txt
D:\\MinIO\\rclone.exe --config "C:\\Users\\admin\\AppData\\Roaming\\rclone\\rclone.conf" copy "{school.storage_path}" "godaddy-backup:/" ^
  --log-file={school.storage_path}\\backup_log.txt ^
  --log-level INFO ^
  --transfers 3 ^
  --tpslimit 2 ^
  --checkers 4 ^
  --retries 10 ^
  --retries-sleep 30s
echo Backup Complete: %date% %time% >> {school.storage_path}\\backup_log.txt"""

def generate_install_agent(school: School) -> str:
    return f"""# EasyReach Agent Installer
# School: {school.name} ({school.code})
# Run as Administrator

$SchoolId = {school.id}
$AgentToken = "{school.agent_token}"
$CentralAPI = "https://mediasync.easylearn.org.in/api"
$AgentPath = "D:\\EasyReachAgent"

Write-Host "Installing EasyReach Agent for {school.name}..."

# Create agent folder
New-Item -ItemType Directory -Force -Path $AgentPath

# Create config file
$config = @{{
    school_id = $SchoolId
    token = $AgentToken
    api_url = $CentralAPI
    storage_path = "{school.storage_path}"
    nginx_port = {school.nginx_port}
    sync_bat = "{school.storage_path}\\sync_aws.bat"
    backup_bat = "D:\\MinIO\\backup.bat"
}}
$config | ConvertTo-Json | Set-Content "$AgentPath\\config.json"

# Install Python dependencies
pip install fastapi uvicorn requests psutil schedule

# Download agent script
Write-Host "Agent configured for {school.name}"
Write-Host "School ID: $SchoolId"
Write-Host "Token: $AgentToken"
Write-Host "Done! Run: python D:\\EasyReachAgent\\agent.py"
"""

def generate_readme(school: School) -> str:
    return f"""EasyReach Setup Guide
School: {school.name} ({school.code})
Generated by ISF Analytica & Informatica Pvt. Ltd.

STEP 1 - Copy files to server
  - nginx.conf → D:\\nginx\\conf\\nginx.conf
  - sync_aws.bat → {school.storage_path}\\sync_aws.bat
  - backup.bat → D:\\MinIO\\backup.bat

STEP 2 - Run install_agent.ps1 as Administrator
  PowerShell -ExecutionPolicy Bypass -File install_agent.ps1

STEP 3 - Start Nginx
  D:\\nginx\\nginx.exe -p D:\\nginx

STEP 4 - Verify
  https://{school.storage_domain}:{school.https_port}/

Support: support@easylearn.org.in
"""

@router.get("/generate/{school_id}")
def generate_configs(
    school_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    school = db.query(School).filter(School.id == school_id).first()
    if not school:
        raise HTTPException(status_code=404, detail="School not found")

    folders = ["easylearn-ncert", "NCERT Course video", "SAAR"]

    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("nginx.conf", generate_nginx_conf(school))
        zf.writestr("sync_aws.bat", generate_sync_bat(school, folders))
        zf.writestr("backup.bat", generate_backup_bat(school))
        zf.writestr("install_agent.ps1", generate_install_agent(school))
        zf.writestr("README.txt", generate_readme(school))

    zip_buffer.seek(0)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename=easyreach_{school.code}_setup.zip"
        }
    )